# Generated by Django 4.0.1 on 2022-05-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusercreationmodel',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
