# Generated by Django 4.0.1 on 2022-04-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('schema', models.CharField(max_length=50)),
                ('Asset_Name', models.CharField(max_length=50)),
                ('Image_before', models.ImageField(upload_to='setup_Model/%Y/%m/%d')),
                ('Image_before2', models.ImageField(upload_to='setup_Model/%Y/%m/%d')),
                ('bias', models.TextField()),
                ('Image_after', models.ImageField(upload_to='setup_Model/%Y/%m/%d')),
                ('Image_after2', models.ImageField(upload_to='setup_Model/%Y/%m/%d')),
                ('be_reason', models.CharField(max_length=100)),
            ],
        ),
    ]
