# Generated by Django 4.0.1 on 2022-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_be_reason_setupmodel_reason_for_be'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='Image_after',
            field=models.ImageField(blank=True, null=True, upload_to='setup_Model/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setupmodel',
            name='Image_after2',
            field=models.ImageField(blank=True, null=True, upload_to='setup_Model/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setupmodel',
            name='Image_before2',
            field=models.ImageField(blank=True, null=True, upload_to='setup_Model/%Y/%m/%d'),
        ),
    ]
