# Generated by Django 4.0.1 on 2022-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_setupmodel_image_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='Reason_For_be',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
