# Generated by Django 4.0.1 on 2022-04-30 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_setupmodel_reason_for_be'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupmodel',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='setupmodel',
            name='tp',
        ),
        migrations.AddField(
            model_name='setupmodel',
            name='result',
            field=models.CharField(choices=[('Tp', 'Tp'), ('Sl', 'Sl')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
