# Generated by Django 4.0.1 on 2022-04-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_setupmodel_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupmodel',
            old_name='Asset_Name',
            new_name='AssetName',
        ),
    ]
