# Generated by Django 4.0.1 on 2022-04-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_asset_name_setupmodel_assetname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupmodel',
            old_name='AssetName',
            new_name='Asset_Name',
        ),
    ]
