# Generated by Django 4.0.1 on 2022-04-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_assetname_setupmodel_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='schema',
            field=models.CharField(choices=[('forex', 'Forex'), ('stock_indices', 'Stock Indices'), ('commodities', 'Commodities'), ('synthetic_indices', 'Synthetic Indices'), ('basket_indices', 'Basket Indices'), ('cryptocurrencies', 'Cryptocurrencies'), ('futures_indices', 'Futures Indices'), ('bond', 'Bond'), ('economy', 'Economy')], max_length=50),
        ),
    ]
