# Generated by Django 4.0.1 on 2022-04-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_setupmodel_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='Reason_For_be',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setupmodel',
            name='schema',
            field=models.CharField(choices=[('basket_indices', 'Basket Indices'), ('bond', 'Bond'), ('cryptocurrencies', 'Cryptocurrencies'), ('economy', 'Economy'), ('forex', 'Forex'), ('futures_indices', 'Futures Indices'), ('stock_indices', 'Stock Indices'), ('synthetic_indices', 'Synthetic Indices')], max_length=50),
        ),
    ]
