# Generated by Django 4.0.1 on 2022-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_setupmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
