# Generated by Django 4.0.1 on 2022-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_setupmodel_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmodel',
            name='schema',
            field=models.CharField(choices=[('Basket Indices', 'Basket Indices'), ('Bond', 'Bond'), ('Cryptocurrencies', 'Cryptocurrencies'), ('Economy', 'Economy'), ('Forex', 'Forex'), ('Futures Indices', 'Futures Indices'), ('Stock Indices', 'Stock Indices'), ('Synthetic Indices', 'Synthetic Indices')], max_length=50),
        ),
    ]
